// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_crawler_schedule

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func CrawlerScheduleResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"crawler": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
			"crawler_config_id": schema.Int64Attribute{
				Computed: true,
			},
			"crawler_last_run_id": schema.Int64Attribute{
				Computed: true,
			},
			"crawler_schedule": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
			"created_at": schema.StringAttribute{
				Computed: true,
			},
			"deleted_at": schema.StringAttribute{
				Computed: true,
			},
			"id": schema.Int64Attribute{
				Computed: true,
			},
			"name": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
			"organization": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
			"project": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
			"project_id": schema.Int64Attribute{
				Computed: true,
			},
			"schedule_cron_string": schema.StringAttribute{
				Required: true,
			},
			"updated_at": schema.StringAttribute{
				Computed: true,
			},
		},
	}
}

type CrawlerScheduleModel struct {
	Crawler            types.String `tfsdk:"crawler"`
	CrawlerConfigId    types.Int64  `tfsdk:"crawler_config_id"`
	CrawlerLastRunId   types.Int64  `tfsdk:"crawler_last_run_id"`
	CrawlerSchedule    types.String `tfsdk:"crawler_schedule"`
	CreatedAt          types.String `tfsdk:"created_at"`
	DeletedAt          types.String `tfsdk:"deleted_at"`
	Id                 types.Int64  `tfsdk:"id"`
	Name               types.String `tfsdk:"name"`
	Organization       types.String `tfsdk:"organization"`
	Project            types.String `tfsdk:"project"`
	ProjectId          types.Int64  `tfsdk:"project_id"`
	ScheduleCronString types.String `tfsdk:"schedule_cron_string"`
	UpdatedAt          types.String `tfsdk:"updated_at"`
}
