// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_project

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func ProjectResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"allow_query_params": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Allow query parameters",
				MarkdownDescription: "Allow query parameters",
			},
			"basic_auth_password": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Basic auth password",
				MarkdownDescription: "Basic auth password",
			},
			"basic_auth_username": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Basic auth username",
				MarkdownDescription: "Basic auth username",
			},
			"disable_revisions": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Disable revisions",
				MarkdownDescription: "Disable revisions",
			},
			"machine_name": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Project machine name",
				MarkdownDescription: "Project machine name",
			},
			"name": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Project name",
				MarkdownDescription: "Project name",
			},
			"organization": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
			"project": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
			"region": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Project region",
				MarkdownDescription: "Project region",
			},
			"with_token": schema.BoolAttribute{
				Optional: true,
				Computed: true,
				Default:  booldefault.StaticBool(false),
			},
		},
	}
}

type ProjectModel struct {
	AllowQueryParams  types.Bool   `tfsdk:"allow_query_params"`
	BasicAuthPassword types.String `tfsdk:"basic_auth_password"`
	BasicAuthUsername types.String `tfsdk:"basic_auth_username"`
	DisableRevisions  types.Bool   `tfsdk:"disable_revisions"`
	MachineName       types.String `tfsdk:"machine_name"`
	Name              types.String `tfsdk:"name"`
	Organization      types.String `tfsdk:"organization"`
	Project           types.String `tfsdk:"project"`
	Region            types.String `tfsdk:"region"`
	WithToken         types.Bool   `tfsdk:"with_token"`
}
