// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_kv_item

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func KvItemResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"key": schema.StringAttribute{
				Required:            true,
				Description:         "Item key",
				MarkdownDescription: "Item key",
			},
			"organization": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Organization identifier",
				MarkdownDescription: "Organization identifier",
			},
			"project": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Project identifier",
				MarkdownDescription: "Project identifier",
			},
			"secret": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Store as secret with KMS encryption. Secrets cannot be retrieved via GET operations (returns [ENCRYPTED]). Ideal for API keys, passwords, and credentials.",
				MarkdownDescription: "Store as secret with KMS encryption. Secrets cannot be retrieved via GET operations (returns [ENCRYPTED]). Ideal for API keys, passwords, and credentials.",
				Default:             booldefault.StaticBool(false),
			},
			"store_id": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
			"success": schema.BoolAttribute{
				Computed: true,
			},
			"value": schema.StringAttribute{
				Required:            true,
				Description:         "Item value (can be JSON string)",
				MarkdownDescription: "Item value (can be JSON string)",
			},
		},
	}
}

type KvItemModel struct {
	Key          types.String `tfsdk:"key"`
	Organization types.String `tfsdk:"organization"`
	Project      types.String `tfsdk:"project"`
	Secret       types.Bool   `tfsdk:"secret"`
	StoreId      types.String `tfsdk:"store_id"`
	Success      types.Bool   `tfsdk:"success"`
	Value        types.String `tfsdk:"value"`
}
