// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_cron_job

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func CronJobResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"application": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The application ID",
				MarkdownDescription: "The application ID",
			},
			"command": schema.ListAttribute{
				ElementType: types.StringType,
				Required:    true,
			},
			"cron": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The cron job ID",
				MarkdownDescription: "The cron job ID",
			},
			"description": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
			"environment": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The environment ID",
				MarkdownDescription: "The environment ID",
			},
			"is_enabled": schema.BoolAttribute{
				Optional: true,
				Computed: true,
				Default:  booldefault.StaticBool(true),
			},
			"name": schema.StringAttribute{
				Required: true,
			},
			"organisation": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The organisation ID",
				MarkdownDescription: "The organisation ID",
			},
			"schedule_expression": schema.StringAttribute{
				Required: true,
			},
			"target_container_name": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
		},
	}
}

type CronJobModel struct {
	Application         types.String `tfsdk:"application"`
	Command             types.List   `tfsdk:"command"`
	Cron                types.String `tfsdk:"cron"`
	Description         types.String `tfsdk:"description"`
	Environment         types.String `tfsdk:"environment"`
	IsEnabled           types.Bool   `tfsdk:"is_enabled"`
	Name                types.String `tfsdk:"name"`
	Organisation        types.String `tfsdk:"organisation"`
	ScheduleExpression  types.String `tfsdk:"schedule_expression"`
	TargetContainerName types.String `tfsdk:"target_container_name"`
}
