// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_domain

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func DomainResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"dns_engaged": schema.Int64Attribute{
				Computed:            true,
				Description:         "DNS engagement status",
				MarkdownDescription: "DNS engagement status",
			},
			"domain": schema.StringAttribute{
				Required:            true,
				Description:         "Domain name",
				MarkdownDescription: "Domain name",
			},
			"id": schema.Int64Attribute{
				Computed:            true,
				Description:         "Domain ID",
				MarkdownDescription: "Domain ID",
			},
			"organization": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Organization identifier",
				MarkdownDescription: "Organization identifier",
			},
			"project": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Project identifier",
				MarkdownDescription: "Project identifier",
			},
		},
	}
}

type DomainModel struct {
	DnsEngaged   types.Int64  `tfsdk:"dns_engaged"`
	Domain       types.String `tfsdk:"domain"`
	Id           types.Int64  `tfsdk:"id"`
	Organization types.String `tfsdk:"organization"`
	Project      types.String `tfsdk:"project"`
}
