// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_ai_governance

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

func AiGovernanceResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Description:         "Manages AI governance configuration for an organization.",
		MarkdownDescription: "Manages AI governance configuration for an organization.",
		Attributes: map[string]schema.Attribute{
			"organization": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Organization machine name (defaults to provider organization)",
				MarkdownDescription: "Organization machine name (defaults to provider organization)",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"ai_enabled": schema.BoolAttribute{
				Required:            true,
				Description:         "Whether AI features are enabled for the organization",
				MarkdownDescription: "Whether AI features are enabled for the organization",
			},
			"model_policy": schema.StringAttribute{
				Required:            true,
				Description:         "Model access policy: unrestricted, allowlist, or blocklist",
				MarkdownDescription: "Model access policy: `unrestricted`, `allowlist`, or `blocklist`",
				Validators: []validator.String{
					stringvalidator.OneOf("unrestricted", "allowlist", "blocklist"),
				},
			},
			"model_list": schema.ListAttribute{
				Optional:            true,
				ElementType:         types.StringType,
				Description:         "List of model identifiers for the allowlist or blocklist policy",
				MarkdownDescription: "List of model identifiers for the allowlist or blocklist policy",
			},
			"mandatory_guardrail_preset": schema.StringAttribute{
				Optional:            true,
				Description:         "Mandatory guardrail preset to enforce on all AI requests",
				MarkdownDescription: "Mandatory guardrail preset to enforce on all AI requests",
			},
			"mandatory_filter_policies": schema.ListAttribute{
				Optional:            true,
				ElementType:         types.StringType,
				Description:         "List of mandatory content filter policy identifiers",
				MarkdownDescription: "List of mandatory content filter policy identifiers",
			},
			"spend_limits": schema.SingleNestedAttribute{
				Optional:            true,
				Description:         "Spend limit configuration for AI usage",
				MarkdownDescription: "Spend limit configuration for AI usage",
				Attributes: map[string]schema.Attribute{
					"monthly_budget_cents": schema.Int64Attribute{
						Optional:            true,
						Description:         "Monthly budget in cents",
						MarkdownDescription: "Monthly budget in cents",
					},
					"daily_budget_cents": schema.Int64Attribute{
						Optional:            true,
						Description:         "Daily budget in cents",
						MarkdownDescription: "Daily budget in cents",
					},
					"per_user_monthly_budget_cents": schema.Int64Attribute{
						Optional:            true,
						Description:         "Per-user monthly budget in cents",
						MarkdownDescription: "Per-user monthly budget in cents",
					},
					"per_user_daily_budget_cents": schema.Int64Attribute{
						Optional:            true,
						Description:         "Per-user daily budget in cents",
						MarkdownDescription: "Per-user daily budget in cents",
					},
					"warning_threshold_percent": schema.Int64Attribute{
						Optional:            true,
						Description:         "Warning threshold as a percentage of budget (0-100)",
						MarkdownDescription: "Warning threshold as a percentage of budget (0-100)",
					},
				},
			},
			"version": schema.Int64Attribute{
				Computed:            true,
				Description:         "Configuration version for optimistic concurrency control",
				MarkdownDescription: "Configuration version for optimistic concurrency control",
			},
		},
	}
}

type AiGovernanceModel struct {
	Organization           types.String `tfsdk:"organization"`
	AiEnabled              types.Bool   `tfsdk:"ai_enabled"`
	ModelPolicy            types.String `tfsdk:"model_policy"`
	ModelList              types.List   `tfsdk:"model_list"`
	MandatoryGuardrailPreset types.String `tfsdk:"mandatory_guardrail_preset"`
	MandatoryFilterPolicies  types.List   `tfsdk:"mandatory_filter_policies"`
	SpendLimits            types.Object `tfsdk:"spend_limits"`
	Version                types.Int64  `tfsdk:"version"`
}

type SpendLimitsModel struct {
	MonthlyBudgetCents       types.Int64 `tfsdk:"monthly_budget_cents"`
	DailyBudgetCents         types.Int64 `tfsdk:"daily_budget_cents"`
	PerUserMonthlyBudgetCents types.Int64 `tfsdk:"per_user_monthly_budget_cents"`
	PerUserDailyBudgetCents   types.Int64 `tfsdk:"per_user_daily_budget_cents"`
	WarningThresholdPercent   types.Int64 `tfsdk:"warning_threshold_percent"`
}

// SpendLimitsAttrTypes returns the attribute type map for the spend_limits
// nested object. Use this with types.ObjectNull() or types.ObjectValueFrom().
func SpendLimitsAttrTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"monthly_budget_cents":          types.Int64Type,
		"daily_budget_cents":            types.Int64Type,
		"per_user_monthly_budget_cents": types.Int64Type,
		"per_user_daily_budget_cents":   types.Int64Type,
		"warning_threshold_percent":     types.Int64Type,
	}
}
