// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_kv_store

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func KvStoreResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"name": schema.StringAttribute{
				Required:            true,
				Description:         "Store name",
				MarkdownDescription: "Store name",
			},
			"organization": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Organization machine name (defaults to provider organization)",
				MarkdownDescription: "Organization machine name (defaults to provider organization)",
			},
			"project": schema.StringAttribute{
				Required:            true,
				Description:         "Project machine name",
				MarkdownDescription: "Project machine name",
			},
			"store_id": schema.StringAttribute{
				Computed:            true,
				Description:         "Store ID",
				MarkdownDescription: "Store ID",
			},
		},
	}
}

type KvStoreModel struct {
	Name         types.String `tfsdk:"name"`
	Organization types.String `tfsdk:"organization"`
	Project      types.String `tfsdk:"project"`
	StoreId      types.String `tfsdk:"store_id"`
}
