// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_crawler

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func CrawlerResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"browser_mode": schema.BoolAttribute{
				Optional: true,
				Computed: true,
			},
			"config": schema.StringAttribute{
				Computed: true,
			},
			"crawler": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
			"created_at": schema.StringAttribute{
				Computed: true,
			},
			"deleted_at": schema.StringAttribute{
				Computed: true,
			},
			"domain": schema.StringAttribute{
				Required: true,
			},
			"domain_verified": schema.Int64Attribute{
				Computed: true,
			},
			"headers": schema.MapAttribute{
				ElementType: types.StringType,
				Required:    true,
			},
			"id": schema.Int64Attribute{
				Computed: true,
			},
			"name": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
			"organization": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
			"project": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
			"project_id": schema.Int64Attribute{
				Computed: true,
			},
			"updated_at": schema.StringAttribute{
				Computed: true,
			},
			"url_list": schema.ListAttribute{
				ElementType: types.StringType,
				Required:    true,
			},
			"uuid": schema.StringAttribute{
				Computed: true,
			},
		},
	}
}

type CrawlerModel struct {
	BrowserMode    types.Bool   `tfsdk:"browser_mode"`
	Config         types.String `tfsdk:"config"`
	Crawler        types.String `tfsdk:"crawler"`
	CreatedAt      types.String `tfsdk:"created_at"`
	DeletedAt      types.String `tfsdk:"deleted_at"`
	Domain         types.String `tfsdk:"domain"`
	DomainVerified types.Int64  `tfsdk:"domain_verified"`
	Headers        types.Map    `tfsdk:"headers"`
	Id             types.Int64  `tfsdk:"id"`
	Name           types.String `tfsdk:"name"`
	Organization   types.String `tfsdk:"organization"`
	Project        types.String `tfsdk:"project"`
	ProjectId      types.Int64  `tfsdk:"project_id"`
	UpdatedAt      types.String `tfsdk:"updated_at"`
	UrlList        types.List   `tfsdk:"url_list"`
	Uuid           types.String `tfsdk:"uuid"`
}
